export const TanpuraTypes = [
  {
    key: "yaksha-shruthi-1",
    title: "Yaksha Shruthi low",
  },
  {
    key: "yaksha-shruthi-2",
    title: "Yaksha Shruthi high",
  },
  {
    key: "traditional-pa",
    title: "Tanpura PA",
  },
  {
    key: "traditional-ma",
    title: "Tanpura MA",
  },
];

export const MusicNotation = [
  {
    id: "c",
    indian: "Sa",
    western: "C",
    kannada: "ಸ",
    kannadaNotation: "ಬಿಳಿ-1",
    fullIndianTitle: "Shadja",
    frequency: 261.63,
  },
  {
    id: "c#",
    indian: "Ri",
    western: "C#",
    kannada: "ರಿ",
    kannadaNotation: "ಕಪ್ಪು-1",
    fullIndianTitle: "Rishabha",
    frequency: 277.18,
  },
  {
    id: "d",
    indian: "Ri",
    western: "D",
    kannada: "ರಿ",
    kannadaNotation: "ಬಿಳಿ-2",
    fullIndianTitle: "Rishabha",
    frequency: 293.66,
  },
  {
    id: "d#",
    indian: "Ga",
    western: "D#",
    kannada: "ಗ",
    kannadaNotation: "ಕಪ್ಪು-2",
    fullIndianTitle: "Gandhara",
    frequency: 311.13,
  },
  {
    id: "e",
    indian: "Ga",
    western: "E",
    kannada: "ಗ",
    kannadaNotation: "ಬಿಳಿ-3",
    fullIndianTitle: "Gandhara",
    frequency: 329.63,
  },
  {
    id: "f",
    indian: "Ma",
    western: "F",
    kannada: "ಮ",
    kannadaNotation: "ಬಿಳಿ-4",
    fullIndianTitle: "Madhyama",
    frequency: 349.23,
  },
  {
    id: "f#",
    indian: "Ma",
    western: "F#",
    kannada: "ಮ",
    kannadaNotation: "ಕಪ್ಪು-3",
    fullIndianTitle: "Madhyama",
    frequency: 369.99,
  },
  {
    id: "g",
    indian: "Pa",
    western: "G",
    kannada: "ಪ",
    kannadaNotation: "ಬಿಳಿ-5",
    fullIndianTitle: "Panchama",
    frequency: 392.0,
  },
  {
    id: "g#",
    indian: "Dha",
    western: "G#",
    kannada: "ದ",
    kannadaNotation: "ಕಪ್ಪು-4",
    fullIndianTitle: "Dhaivata",
    frequency: 415.3,
  },
  {
    id: "a",
    indian: "Dha",
    western: "A",
    kannada: "ದ",
    kannadaNotation: "ಬಿಳಿ-6",
    fullIndianTitle: "Dhaivata",
    frequency: 440.0,
  },
  {
    id: "a#",
    indian: "Ni",
    western: "A#",
    kannada: "ನಿ",
    kannadaNotation: "ಕಪ್ಪು-5",
    fullIndianTitle: "Nishada",
    frequency: 466.16,
  },
  {
    id: "b",
    indian: "Ni",
    western: "B",
    kannada: "ನಿ",
    kannadaNotation: "ಬಿಳಿ-7",
    fullIndianTitle: "Nishada",
    frequency: 493.88,
  },
];
